steps:
  - name: 'docker/compose:1.19.0'
    args: ['up','-d']
  - name: 'gradle:8-jdk17'
    args: ['gradle', 'clean', 'test']
  - name: 'docker/compose:1.19.0'
    args: ['down']
options:
  logging: CLOUD_LOGGING_ONLY